#!/usr/bin/env ruby

# Generate a table of 16-bit colors from hex values.

# http://www.colourlovers.com/palette/3645341/Window_seat
colors_rgb = %w(
  B64E47
  4E2C20
  B5A09D
)

puts <<-EOS
; DO NOT EDIT
; Generated by #{__FILE__}
EOS

colors_rgb.map do |c|
  r,g,b = *c.scan(/../)
    .map {|x| x.to_i(16) / (2 ** 3) } # Down sample from 256 to 32 range.

  # Line them up within the 16 bits we have.
  high = b << 2
  high |= g >> 3
  low = (g << 5) & 0xFF
  low |= r

  puts ".DW %" + [high, low].map {|x| "%08i" % x.to_s(2).to_i }.join
end

puts <<-EOS
.DEFINE const_num_colors #{colors_rgb.length}
.EXPORT const_num_colors
EOS
